// Native lifecycle/DSP checks. Test banks below are deterministic signals;
// --render uses the actual decoded inherited recordings for the sound preview.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),constants=JSON.parse(fs.readFileSync(path.join(root,'src/constants.json')));
const actualBankFolder=process.env.ASHFALL_AUDIO_BANK_DIR?path.resolve(process.env.ASHFALL_AUDIO_BANK_DIR):null;
class Param{constructor(value=0){this.value=value;}setTargetAtTime(v){assert(Number.isFinite(v));this.value=v;}cancelScheduledValues(){}setValueAtTime(v){this.value=v;}}
class Node{constructor(ctx,type){this.ctx=ctx;this.type=type;this.links=[];for(const k of['gain','frequency','pan','playbackRate','Q','positionX','positionY','positionZ'])this[k]=new Param(k==='gain'||k==='playbackRate'?1:0);}connect(n){this.links.push(n);return n;}disconnect(){this.links=[];}start(){this.started=true;}stop(t=this.ctx.currentTime){this.stopped=true;this.stopTime=t;if(t<=this.ctx.currentTime)this.onended?.();}}
class Context{constructor(){this.currentTime=0;this.sampleRate=24000;this.allocations=0;}node(type){return new Node(this,type);}createGain(){return this.node('gain');}createBiquadFilter(){return this.node('filter');}createStereoPanner(){return this.node('stereo');}createPanner(){return this.node('hrtf');}createBufferSource(){return this.node('source');}createConvolver(){return this.node('reverb');}createBuffer(ch,length,sr){this.allocations++;const d=Array.from({length:ch},()=>new Float32Array(length));return {length,numberOfChannels:ch,duration:length/sr,sampleRate:sr,getChannelData:i=>d[i]};}}
const fixtureBanks=new WeakMap();
function bank(ctx,cues,file){if(!file&&fixtureBanks.has(cues))return fixtureBanks.get(cues);const duration=Math.max(...Object.values(cues).map(q=>q.start+q.duration))+.1;if(file){const bytes=fs.readFileSync(file),data=new Float32Array(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));return {length:data.length,duration:data.length/24000,numberOfChannels:1,sampleRate:24000,getChannelData:()=>data};}const b=ctx.createBuffer(1,Math.ceil(duration*ctx.sampleRate),ctx.sampleRate),d=b.getChannelData(0);for(const q of Object.values(cues))for(let i=Math.ceil(q.start*ctx.sampleRate);i<Math.floor((q.start+q.duration)*ctx.sampleRate);i++){const t=i/ctx.sampleRate-q.start;d[i]=Math.min(1,t/.02)*Math.min(1,(q.duration-t)/.03)*(.29*Math.sin(t*790+Math.sin(t*25)*2)+.08*Math.sin(t*7900));}fixtureBanks.set(cues,b);return b;}
function fixture({stereo=false,mono=false,actual=false}={}){const ctx=new Context();if(stereo||mono)ctx.createPanner=null;if(mono)ctx.createStereoPanner=null;const folder=actualBankFolder;if(actual)assert(folder,'Set ASHFALL_AUDIO_BANK_DIR to a folder containing approved.f32, fx.f32 and monster.f32 (24 kHz mono float32 PCM).');const audio={ctx,active:true,prepare:()=>Promise.resolve(true),reset(){},play(){},sfx:ctx.createGain(),music:ctx.createGain(),ambience:ctx.createGain(),heartSilenceMusic(){}};audio.approvedBank=bank(ctx,constants.CREATURE_AUDITION_CUES,actual?path.join(folder,'approved.f32'):null);audio.bank=bank(ctx,constants.AUDIO_CUES,actual?path.join(folder,'fx.f32'):null);audio.monsterBank=bank(ctx,constants.CREATURE_AUDIO_CUES,actual?path.join(folder,'monster.f32'):null);
const room={id:'bath',room:true,z:0,h:8,ceil:8,bounds:[0,0,30,30],acoustic:'pool',ambience:'silent',water:.3},far={...room,id:'far',bounds:[100,100,130,130]},RS={active:{z:0,room:'bath'}},RW={surfaces:[room,far],solids:[],portals:[],emitters:[],byId:{bath:room,far}},player={x:5,y:5,a:0},c={...constants,audio,RS,RW,player,RS_EYE:1.55,mode:'playing',console,rsGround:()=>room};vm.createContext(c);for(const file of['restroom-water-samples.js','restroom-audio.js','restroom-threat-audio.js'])vm.runInContext(fs.readFileSync(path.join(root,'src',file),'utf8'),c);const run=s=>vm.runInContext(s,c),enemy=(kind='hollow',id='test',x=8,y=7,z=1.94)=>({id,kind,x,y,z,roomId:'bath',normal:{x:0,y:0,z:1},alive:true});run('rsAudioMix(true);rsThreatAudioWarm()');const tick=n=>{ctx.currentTime+=n;run('rsThreatAudioUpdate(.05);rsAudioRetireExpired()');};return {ctx,audio,c,run,enemy,player,RS,RW,tick};}
let count=0;function test(name,fn){if(process.env.ASHFALL_AUDIO_CASE&&!name.includes(process.env.ASHFALL_AUDIO_CASE))return;fn();count++;console.log('PASS '+name);}
test('14 cached Hollow event takes are finite, distinct and avoid clipped endpoints',()=>{const f=fixture();assert.equal(f.run('RST_AUDIO.buffers.size'),14);const ids=new Set;for(const [key,b]of f.run('[...RST_AUDIO.buffers]')){const d=b.getChannelData(0);assert(d.every(Number.isFinite));assert.equal(d[0],0);assert.equal(d.at(-1),0);assert(Math.max(...d)<=.851&&Math.min(...d)>=-.851);assert(b.duration<=1.8);ids.add(require('crypto').createHash('sha256').update(Buffer.from(d.buffer)).digest('hex'));}assert.equal(ids.size,14);});
test('no PCM allocation during voices, movement updates or repeated attacks',()=>{const f=fixture(),before=f.ctx.allocations;for(let i=0;i<20;i++){f.c.e=f.enemy('hollow','e');f.ctx.currentTime+=.70;f.run("rsThreatVoice(e,'charge');rsThreatVoiceUpdate(e)");}assert.equal(f.ctx.allocations,before);assert(f.run('RST_AUDIO.stats.played')>5);});
test('charge articulation has appreciably more waveform energy than its warning breath',()=>{const f=fixture(),energy=b=>b.getChannelData(0).reduce((s,x)=>s+x*x,0)/b.length;assert(energy(f.run("RST_AUDIO.buffers.get('hollow:charge:0')"))>energy(f.run("RST_AUDIO.buffers.get('hollow:breathe:0')"))*1.6);});
test('voices follow moving sources in all three axes and inherit local reverb',()=>{const f=fixture();f.c.e=f.enemy();const v=f.run("rsThreatVoice(e,'charge')");assert(v.hrtf);assert(v.panner.positionY.value>0);assert(v.send.links.includes(f.run('RS_AUDIO.verb')));const initial=v.level.gain.value;f.c.e.x=6;f.c.e.y=4;f.c.e.z=6;f.run('rsThreatVoiceUpdate(e)');assert(v.panner.positionX.value<0&&v.panner.positionY.value>4);assert.notEqual(v.level.gain.value,initial);
 f.run('const countPosition=rsAudioPosition;let positionCalls=0;rsAudioPosition=function(...args){positionCalls++;return countPosition(...args);};rsThreatAudioUpdate(.05);');
 assert.equal(f.run('positionCalls'),1,'each active owner receives one spatial update');
 f.run('rsThreatAudioStop();positionCalls=0;rsThreatVoiceUpdate(e);');assert.equal(f.run('positionCalls'),0,'silent owners do not trace occlusion');
});
test('walls and other floors attenuate and muffle voices; disconnected rooms are silent',()=>{const f=fixture();f.c.e=f.enemy('hollow','e',10,5);const v=f.run("rsThreatVoice(e,'charge')"),before=v.level.gain.value;f.RW.solids.push({x1:7,x2:7.2,y1:0,y2:30,z:0,h:8});f.run('rsThreatVoiceUpdate(e)');assert(v.level.gain.value<before*.5);assert(v.filter.frequency.value<=850);f.c.e.roomId='far';f.run('rsThreatVoiceUpdate(e)');assert(v.ended);});
test('scaled giant mouth produces the correct spatial elevation',()=>{const f=fixture();f.c.e={...f.enemy(),scale:2.05,forward:{x:0,y:1,z:0},phase:'charge'};let p=f.run('rsThreatPosition(e)');assert(Math.abs(p.z-(f.c.e.z+.61*2.05))<1e-7);assert(Math.abs(p.y-(f.c.e.y+.44*2.05))<1e-7);const v=f.run("rsThreatVoice(e,'charge')");assert(v.hrtf&&v.panner.positionY.value>1.6);});
test('unavailable audio, pause, other chapter and unknown event are safe no-ops',()=>{const f=fixture();f.c.e=f.enemy();f.audio.active=false;assert.equal(f.run("rsThreatVoice(e,'attack')"),null);f.audio.active=true;f.run('RS_AUDIO.domain="transfer"');assert.equal(f.run("rsThreatVoice(e,'attack')"),null);f.run('RS_AUDIO.domain="restrooms"');assert.equal(f.run("rsThreatVoice(e,'nonsense')"),null);f.run('RS_AUDIO.ctx=null');assert.equal(f.run("rsThreatVoice(e,'attack')"),null);});
test('pellet hits produce a single pain voice and damage interrupts an attack immediately',()=>{const f=fixture();f.c.e=f.enemy();f.run("rsThreatVoice(e,'attack')");for(let i=0;i<20;i++)f.run("rsThreatVoice(e,'hit')");assert.equal(f.run('RST_AUDIO.stats.played'),2);assert.equal(f.run('[...RST_AUDIO.voices][0].event'),'hit');f.tick(.2);f.run("rsThreatVoice(e,'hit')");assert.equal(f.run('RST_AUDIO.stats.played'),3);});
test('breathing never interrupts an attack and a new charge replaces an old breath',()=>{const f=fixture();f.c.e=f.enemy();f.run("rsThreatVoice(e,'breathe')");f.tick(.1);f.run("rsThreatVoice(e,'charge')");assert.equal(f.run('[...RST_AUDIO.voices][0].event'),'charge');f.run("rsThreatVoice(e,'breathe')");assert.equal(f.run('RST_AUDIO.stats.played'),2);f.run("rsThreatVoice(e,'attack')");assert.equal(f.run('[...RST_AUDIO.voices][0].event'),'attack');});
test('only one active throat is retained, with a close warning replacing distant breathing',()=>{const f=fixture();f.c.e=f.enemy('hollow','distant',18,8);f.run("rsThreatVoice(e,'breathe')");f.tick(.13);assert.equal(f.run('RST_AUDIO.voices.size'),1);f.c.e=f.enemy('hollow','near',6,6);f.run("rsThreatVoice(e,'charge')");assert.equal(f.run('RST_AUDIO.voices.size'),1);assert(f.run('[...RST_AUDIO.voices].some(v=>v.ownerId==="near")'));assert.equal(f.run('RST_AUDIO.stats.peakVoices'),1);});
test('voice interruption has a bounded 18 ms fade and leaves no expired source tails',()=>{const f=fixture();f.c.e=f.enemy();const old=f.run("rsThreatVoice(e,'breathe')");f.tick(.1);f.run("rsThreatVoice(e,'charge')");assert(old.retiring);assert(old.stopTime===undefined);assert(Math.abs(old.source.stopTime-f.ctx.currentTime-.018)<1e-8);assert.equal(old.level.gain.value,0);assert.equal(f.run('RST_AUDIO.tails.size'),1);f.tick(.03);assert(old.ended);assert.equal(f.run('RST_AUDIO.tails.size'),0);assert.equal(f.run('RST_AUDIO.voices.size'),1);});
test('only the seven supported Hollow events are cached and accepted',()=>{const f=fixture();assert.deepEqual(Array.from(f.run('Object.keys(RST_EVENTS)')),['awake','breathe','charge','windup','attack','hit','death']);f.c.e=f.enemy('unsupported');assert.equal(f.run("rsThreatVoice(e,'charge')"),null);assert.equal(f.run("rsThreatBake('unsupported','charge')"),null);f.c.e=f.enemy();assert.equal(f.run("rsThreatVoice(e,'unavailable-contact')"),null);assert.equal(f.run('RST_AUDIO.voices.size'),0);});
test('distant cries are culled and shared graph reserves space for movement water',()=>{const f=fixture();f.c.e=f.enemy('hollow','far',100,100);assert.equal(f.run("rsThreatVoice(e,'attack')"),null);f.c.e=f.enemy();f.run('for(let i=0;i<22;i++)rsAudioVoice(rsAudioBuffer("water-motion",0),{kind:"water-motion"})');assert.equal(f.run("rsThreatVoice(e,'attack')"),null);assert.equal(f.run('RS_AUDIO.voices.size'),22);assert.equal(f.run('RST_AUDIO.voices.size'),0);});
test('stopping one creature releases its nodes; stopping chapter releases all bookkeeping',()=>{const f=fixture();f.c.e=f.enemy();const v=f.run("rsThreatVoice(e,'charge')");f.run('rsThreatAudioStop(e.id)');assert(v.ended&&v.source.stopped);assert(v.nodes.every(n=>n.links.length===0));assert.equal(f.run('RS_AUDIO.voices.size'),0);f.ctx.currentTime=1;f.run("rsThreatVoice(e,'charge');rsAudioStop();rsThreatAudioUpdate(.1)");assert.equal(f.run('RST_AUDIO.voices.size'),0);assert.equal(f.run('RST_AUDIO.owners.size'),0);});
test('dead throat one-shot may finish while its entity remains dead, and ended voices retire',()=>{const f=fixture();f.c.e=f.enemy();f.c.e.alive=false;const v=f.run("rsThreatVoice(e,'death')");assert(v);f.tick(.5);assert(!v.ended);f.tick(2);assert(v.ended);assert.equal(f.run('RS_AUDIO.voices.size+RST_AUDIO.voices.size'),0);});
test('stereo panning and mono fallback preserve cues without HRTF support',()=>{for(const opts of[{stereo:true},{mono:true}]){const f=fixture(opts);f.c.e=f.enemy();const v=f.run("rsThreatVoice(e,'charge')");assert(v&&!v.hrtf);if(opts.stereo)assert(v.panner.pan.value>0);else assert.equal(v.panner,null);}});
test('late bank identity replacement rebuilds once, and repeat warmups reuse buffers',()=>{const f=fixture(),first=f.run('RST_AUDIO.buffers.get("hollow:charge:0")'),before=f.ctx.allocations;f.run('rsThreatAudioWarm();rsThreatAudioWarm()');assert.equal(f.ctx.allocations,before);f.audio.approvedBank={...f.audio.approvedBank};f.run('rsThreatAudioWarm()');assert.notStrictEqual(first,f.run('RST_AUDIO.buffers.get("hollow:charge:0")'));const after=f.ctx.allocations;f.run('rsThreatAudioWarm()');assert.equal(f.ctx.allocations,after);});
test('approved recorded water and dry Foley outputs retain verified beta 0.2.6 hashes',()=>{const expected={
 'restroom-audio.js':'cfe032345a031122d4987121f363e402746d7efa6a85b478171c62abe79ea966',
 'restroom-water-samples.js':'af173dd32d65307cb899d1aeafeea0c591b754bcc8b68908f53dc19602a0f9e4'
};for(const [name,hash]of Object.entries(expected))assert.equal(require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,'src',name))).digest('hex'),hash,name+' changed');});
test('full runtime mouth audio follows the rendered giant rotation',()=>{const r=require('./runtime_harness.cjs')(),near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);r.context.audioEntity={kind:'hollow',x:10,y:20,z:1.94,scale:2.05,normal:{x:0,y:0,z:1},forward:{x:-1,y:0,z:0},phase:'charge',roomId:'R05'};let p=r.eval('rsThreatPosition(audioEntity)');near(p.x,10-.44*2.05);near(p.y,20-.035*2.05);near(p.z,1.94+.61*2.05);});
test('every retained Hollow take is sample-identical to the approved beta 0.2.7 DSP output',()=>{const expected={
 "hollow:awake:0": "24686d6a2c859c747340d0db16158b9b79820b0334b53339640ec19ee5801b48",
 "hollow:awake:1": "fa207dcb1ce83e141a26953d939ae25999da393d15079b9625a7cdd648de4041",
 "hollow:breathe:0": "e63086946e3421e0d7ed9590866756793c58c50ffe60ce5aa0ac6826c1ad1351",
 "hollow:breathe:1": "989b1e4ffb382c990fc8dac8609f13157ae46ff86429243e97305f147af80cb4",
 "hollow:charge:0": "2ceb2af31a1b67c3402f5b39766736ab3bc0e5b160606ab56580701a0a03109e",
 "hollow:charge:1": "1465fda289e09e4e59824b1466f501b907bba78127274d8a368ca53d2a6a2d5e",
 "hollow:windup:0": "318c24849550260c03dc279d3a90500c99e74c21252dd0d7bc750b0387497bcc",
 "hollow:windup:1": "83551d165ac75a24604f254fafa7e6afd19753a20b859ef4ea87236dd80759c5",
 "hollow:attack:0": "4f989f014ef5d2e81be35de4508fa5eb1e7a15f9006674fa78ebc4dc5639a5c7",
 "hollow:attack:1": "d88df0cfecd446df98b0a3b12d67717f335171256e7ee9ff949337baf7747fae",
 "hollow:hit:0": "5305b29f207ce2f59909df6da06490ace696eb489fac58b9159f177e42cf56cb",
 "hollow:hit:1": "108c51043460d4c660bd3c77fb53dfc2f9484476efaccdf300a2b3e128162c81",
 "hollow:death:0": "6343a39387496ba88546ca8449c0acc882f5aca2e0a553c2249f7c3268d55251",
 "hollow:death:1": "bf2b288d4ea226ea2467e1c214c497d7105364a44caba2f35abe99621ccf7521"
};const f=fixture();for(const [key,hash]of Object.entries(expected)){const b=f.run(`RST_AUDIO.buffers.get('${key}')`);assert.equal(require('crypto').createHash('sha256').update(Buffer.from(b.getChannelData(0).buffer)).digest('hex'),hash,key+' changed');}});
console.log(count+' threat-audio DSP/lifecycle checks passed; no human listening or browser test claimed.');
if(process.argv.includes('--render')){
 const f=fixture({actual:true});const folder=process.env.ASHFALL_AUDIO_PREVIEW_DIR?path.resolve(process.env.ASHFALL_AUDIO_PREVIEW_DIR):actualBankFolder;fs.mkdirSync(folder,{recursive:true});
 const manifest={sampleRate:24000,method:'Exact runtime-baked PCM with inherited decoded recordings. Preview uses offline room convolution and equal-power stereo pan; live HRTF, occlusion, master limiter and live AI timing are not simulated.',events:[]};
 for(const event of Object.keys(f.run('RST_EVENTS'))){const b=f.run(`RST_AUDIO.buffers.get('hollow:${event}:0')`);fs.writeFileSync(path.join(folder,'hollow-'+event+'.f32'),Buffer.from(b.getChannelData(0).buffer));}
 for(const preset of['pool']){const b=f.run(`rsAudioImpulse('${preset}')`);for(let ch=0;ch<2;ch++)fs.writeFileSync(path.join(folder,preset+'-reverb-'+ch+'.f32'),Buffer.from(b.getChannelData(ch).buffer));}
 fs.writeFileSync(path.join(folder,'preview-method.json'),JSON.stringify(manifest,null,2));console.log('Actual-bank PCM and impulse responses exported for preview.');
}
