// audio.js — bundled from the owner’s liminal baseline.
// Visceral mix: recorded one-shots, HRTF positioning, occlusion, convolution,
// and separate transient/voice/music headroom. Sources and licenses in Credits.
const audio={ctx:null,bank:null,scoreBuffer:null,ready:null,active:false,voices:[],loops:[],lastFoot:0,lastBreath:0,lastHeart:0,lastAmbient:0,lastTick:0,lastVocal:0,painUntil:0,variation:{},
 init(){if(this.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const a=this.ctx=new AC();
 this.master=a.createGain();this.master.gain.value=.86;
 this.sfx=a.createGain();this.music=a.createGain();this.musicDuck=a.createGain();this.ambience=a.createGain();this.shock=a.createBiquadFilter();this.shock.type='lowpass';this.shock.frequency.value=19500;this.shock.Q.value=.5;
 this.sfx.connect(this.shock);this.ambience.connect(this.shock);this.music.connect(this.musicDuck).connect(this.shock);this.shock.connect(this.master);
 const bass=a.createBiquadFilter();bass.type='lowshelf';bass.frequency.value=130;bass.gain.value=2;
 const limiter=a.createDynamicsCompressor();limiter.threshold.value=-3;limiter.knee.value=3;limiter.ratio.value=16;limiter.attack.value=.002;limiter.release.value=.12;
 const ceiling=a.createWaveShaper();ceiling.curve=Float32Array.from({length:4096},(_,i)=>.965*Math.tanh((i/4095*2-1)*1.05)/Math.tanh(1.05));ceiling.oversample='2x';this.master.connect(bass).connect(limiter).connect(ceiling).connect(a.destination);
 this.room=a.createConvolver();this.room.normalize=false;this.room.buffer=this.impulse(2.65);
 this.roomTone=a.createBiquadFilter();this.roomTone.type='lowpass';this.roomTone.frequency.value=3700;
 this.roomReturn=a.createGain();this.roomReturn.gain.value=.62;this.room.connect(this.roomTone).connect(this.roomReturn).connect(this.sfx);
 this.musicTone=a.createBiquadFilter();this.musicTone.type='lowpass';this.musicTone.frequency.value=11500;this.musicTone.connect(this.music);this.musicBed=a.createGain();this.musicBed.gain.value=1;this.musicBed.connect(this.musicTone);this.impShort=this.room.buffer;this.impLong=this.impulse(7.4);
 this.levels();
 },
 impulse(seconds){const a=this.ctx,b=a.createBuffer(2,Math.ceil(a.sampleRate*seconds),a.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);let low=0;for(let i=0;i<d.length;i++){const t=i/a.sampleRate;low=low*.48+rand(-1,1)*.52;d[i]=low*.0075*Math.exp(-t*3.1)*(t>.013?1:0);}for(const [delay,amp]of[[.021,.42],[.039,.29],[.068,.2],[.109,.16],[.173,.1]])d[Math.floor((delay+ch*.0037)*a.sampleRate)]+=amp;}return b;},
 prepare(){if(this.ready)return this.ready;try{this.init();if(!this.ctx)return Promise.resolve(false);const decode=url=>loadAudioAsset(url,this.ctx);this.ready=Promise.all([decode(AUDIO_DATA.fx),decode(AUDIO_DATA.music),decode(HEART_AUDIO_DATA),decode(NIGHT_AUDIO_DATA.insects),decode(NIGHT_AUDIO_DATA.owl),decode(CERBERUS_AUDIO_DATA)]).then(([fx,music,heart,insects,owl,cerberus])=>{this.bank=fx;this.scoreBuffer=music;this.heartBuffer=heart;this.nightBuffers={insects,owl};this.cbScoreBuffer=cerberus;return true;});return this.ready;}catch(e){this.ready=Promise.reject(e);return this.ready;}},
 levels(){if(!this.ctx)return;const t=this.ctx.currentTime;this.master.gain.setTargetAtTime(settings.mute?0:.86,t,.025);this.sfx.gain.setTargetAtTime(settings.sfx,t,.035);this.music.gain.setTargetAtTime(settings.music*.92*((review.active||mode==='review')&&!review.music?0:1),t,.06);this.ambience.gain.setTargetAtTime(settings.sfx*(liminal.target?.03:hbVictory()?.055:.19),t,.08);},
 start(){this.init();if(!this.ctx)return;if(mode!=='playing')this.heartPresentationReset();if(hbFighting()&&mode!=='playing'&&this.hrt){this.hrt.pulse.gain.cancelScheduledValues(this.ctx.currentTime);this.hrt.pulse.gain.setValueAtTime(.0001,this.ctx.currentTime);}this.ctx.resume().catch(()=>{});this.active=true;this.levels();this.prepare().then(ok=>{if(ok&&this.active&&!this.loops.length)this.startLoops();}).catch(()=>feed('AUDIO COULD NOT START // RELOAD GAME'));},
 startLoops(){const a=this.ctx,s=a.createBufferSource();s.buffer=this.scoreBuffer;s.loop=true;s.connect(this.musicBed);s.start(a.currentTime);this.loops.push(s);for(const key of['roomtone','machinery']){const c=AUDIO_CUES[key];if(!c)continue;const n=a.createBufferSource(),g=a.createGain();n.buffer=this.bank;n.loop=true;n.loopStart=c.start;n.loopEnd=c.start+c.duration;g.gain.value=key==='roomtone'?.78:.27;n.connect(g).connect(this.ambience);n.start(a.currentTime,c.start);this.loops.push(n);}this.lastFoot=this.lastBreath=this.lastHeart=this.lastAmbient=0;this.heartScoreFrame();if(HB.state==='dying')this.heartDeathStart();},
 pause(){this.active=false;if(this.ctx)this.ctx.suspend().catch(()=>{});},
 reset(){this.heartPresentationReset();for(const n of this.loops){try{n.stop();n.disconnect();}catch{}}this.loops=[];for(const v of [...this.voices]){try{v.source.stop();}catch{}}this.voices=[];this.restoreRoom();this.sourcelessClock=6;this.lastFoot=this.lastBreath=this.lastHeart=this.lastAmbient=this.lastTick=0;this.painVoice=null;this.painUntil=0;this.lastVocal=0;if(this.ctx){this.musicDuck.gain.cancelScheduledValues(this.ctx.currentTime);this.musicDuck.gain.value=1;this.shock.frequency.value=19500;}},
 choose(prefix,n){let k=Math.floor(Math.random()*n);if(n>1&&k===this.variation[prefix])k=(k+1)%n;this.variation[prefix]=k;return prefix+k;},
 play(key,{vol=1,rate=1,at=0,pos=null,wet=.2,pan=0,bus=null,follow=null}={}){if(!this.ctx||!this.bank)return null;const c=AUDIO_CUES[key];if(!c)return null;const a=this.ctx,t=Math.max(a.currentTime,at||a.currentTime),source=a.createBufferSource(),gain=a.createGain(),filter=a.createBiquadFilter();source.buffer=this.bank;source.playbackRate.value=rate;filter.type='lowpass';filter.frequency.value=19000;filter.Q.value=.5;gain.gain.value=vol;source.connect(filter).connect(gain);const nodes=[source,gain,filter];let panner=null;
 if(pos&&a.createPanner){panner=a.createPanner();panner.panningModel='HRTF';panner.distanceModel='inverse';panner.refDistance=1;panner.rolloffFactor=0;panner.maxDistance=60;gain.connect(panner).connect(bus||this.sfx);nodes.push(panner);}else if(a.createStereoPanner){panner=a.createStereoPanner();panner.pan.value=pan;gain.connect(panner).connect(bus||this.sfx);nodes.push(panner);}else gain.connect(bus||this.sfx);
 const send=a.createGain();send.gain.value=wet;gain.connect(send).connect(this.room);nodes.push(send);
 const v={source,gain,filter,panner,pos:pos?{...pos}:null,follow,vol,send,wet,nodes,until:t+c.duration/rate+.08};if(pos)this.position(v,t);this.voices.push(v);source.onended=()=>{for(const n of nodes)try{n.disconnect();}catch{}const i=this.voices.indexOf(v);if(i>=0)this.voices.splice(i,1);};source.start(t,c.start,c.duration);if(this.voices.length>70){const oldest=this.voices.find(x=>x!==v);if(oldest)try{oldest.source.stop();}catch{}}return v;},
 position(v,t){if(!v.pos)return;const p=v.follow&&v.follow.alive?v.follow:v.pos,dx=p.x-player.x,dy=p.y-player.y,d=Math.hypot(dx,dy),blocked=!v.night&&!lineOfSight(player.x,player.y,p.x,p.y),x=(dy*Math.cos(player.a)-dx*Math.sin(player.a))*1.7,z=-(dx*Math.cos(player.a)+dy*Math.sin(player.a))*1.7;
 const atten=1/(1+d*(v.night?.055:.21))*(blocked?.33:1);v.gain.gain.setTargetAtTime(v.vol*atten,t,.045);v.filter.frequency.setTargetAtTime(v.night?2200:blocked?850:Math.max(3000,17000-d*750),t,.05);v.send.gain.setTargetAtTime(v.wet*(blocked?1.9:1+d*.05),t,.07);
 if(v.panner?.positionX){v.panner.positionX.setTargetAtTime(x,t,.025);v.panner.positionY.setTargetAtTime((p.z||.5)-.52,t,.025);v.panner.positionZ.setTargetAtTime(z,t,.025);}else if(v.panner?.pan)v.panner.pan.setTargetAtTime(clamp(x/(d*1.7+.1),-1,1),t,.025);},
 duck(amount=.65,duration=.2){if(!this.ctx)return;const t=this.ctx.currentTime,g=this.musicDuck.gain;g.cancelScheduledValues(t);g.setTargetAtTime(amount,t,.009);g.setTargetAtTime(1,t+duration,.12);},
 fire(w){if(!this.active)return;const t=this.ctx?.currentTime||0;if(w===0){this.play(this.choose('shotgun',3),{vol:1.0,rate:rand(.965,1.03),wet:.32});this.play('rack',{vol:.48,at:t+.19,wet:.13,pan:.12});this.play('shell',{vol:.27,at:t+.37,wet:.25,pan:.7});this.duck(.48,.16);}else if(w===1){this.play(this.choose('plasma',3),{vol:.58,rate:rand(.96,1.05),wet:.2,pan:rand(-.06,.06)});this.duck(.79,.055);}else{this.play(this.choose('cannon',2),{vol:1.12,wet:.5});this.duck(.38,.4);}},
 boom(strength=1,position=null){this.play(this.choose('blast',2),{vol:Math.min(1.15,strength),pos:typeof position==='object'?position:null,wet:.54,rate:rand(.91,1.02)});this.duck(.48,.25);},
 creature(e,attack=false){if(!this.active||!this.ctx)return;const d=Math.hypot(e.x-player.x,e.y-player.y);if(d>16)return;const t=this.ctx.currentTime;if(!attack&&t-this.lastVocal<.55)return;this.lastVocal=t;const prefix=e.type===0?(attack?'scream':'patient'):e.type===1?(attack?'shriek':'crawler'):(attack?'roar':'brute');const counts={scream:2,patient:3,shriek:2,crawler:3,roar:2,brute:3};this.play(this.choose(prefix,counts[prefix]),{vol:attack?1.05:.7,pos:e,follow:e,rate:rand(.93,1.06),wet:attack?.4:.55});},
 flesh(e=null,heavy=false){this.play(this.choose(heavy?'gore':'flesh',heavy?3:3),{vol:heavy?.8:.4,pos:e,wet:.18,rate:rand(.9,1.12)});},
 kill(e=null){this.flesh(e,true);if(e&&Math.random()<.6)this.play(this.choose('death',3),{vol:.64,pos:e,wet:.4,rate:e.type===2?.7:e.type===1?1.2:.9});},
 hit(amount=15){if(!this.ctx)return;const t=this.ctx.currentTime;this.play(this.choose('bodyhit',3),{vol:.83,wet:.14});if(t>this.painUntil){if(this.painVoice){this.painVoice.gain.gain.setTargetAtTime(.001,t,.015);try{this.painVoice.source.stop(t+.07);}catch{}}this.painVoice=this.play(this.choose('pain',4),{vol:1.0,wet:.09,rate:rand(.94,1.025)});this.painUntil=t+.55;}if(player.hp<35)this.play('gasp',{vol:.58,at:t+.4,wet:.08});this.duck(.24,.5);this.shock.frequency.cancelScheduledValues(t);this.shock.frequency.setTargetAtTime(4200,t,.008);this.shock.frequency.setTargetAtTime(19500,t+.19,.28);},
 dash(){this.play('dash',{vol:.64,wet:.2});this.play('effort',{vol:.32,wet:.035,rate:rand(.94,1.07)});},
 swing(){this.play('swing',{vol:.62,wet:.18});this.play('effort',{vol:.3,wet:.02,rate:1.08});},
 reload(phase='start'){this.play(phase==='end'?'rack':'reload',{vol:.5,wet:.12,pan:.12});},
 dry(){this.play('dry',{vol:.5,wet:.09});},
 pickup(){this.play('pickup',{vol:.28,wet:.38});},
 seal(){this.play('seal',{vol:.85,wet:.65});this.duck(.4,.7);},
 tick(){if(!this.active||!this.ctx||!this.bank||mode!=='playing')return;const t=this.ctx.currentTime;if(t-this.lastTick>.05){this.lastTick=t;for(const v of this.voices)if(v.pos)this.position(v,t);this.musicTone.frequency.setTargetAtTime(9500+stage*1500,t,.3);}
 const speed=Math.hypot(player.vx,player.vy);if(speed>.9&&dashT<=0&&t-this.lastFoot>.29/Math.max(.8,speed/4.65)){this.lastFoot=t;this.play(this.choose('step',4),{vol:.27+speed*.018,wet:.25,pan:this.variation.step%2?.12:-.12,rate:rand(.92,1.07)});}
 if(player.hp<38&&t-this.lastHeart>(player.hp<20?.48:.64)){this.lastHeart=t;this.play('heartbeat',{vol:(1-player.hp/65)*.55,wet:0});}
 if((player.hp<45||speed>5)&&t-this.lastBreath>(player.hp<25?2.1:4.3)&&t>this.painUntil+.5){this.lastBreath=t;this.play(this.choose('breath',3),{vol:player.hp<25?.64:.32,wet:.06});}
 if(t-this.lastAmbient>rand(4,7)){this.lastAmbient=t;const loc=environmentProps?.find(p=>Math.hypot(p.x-player.x,p.y-player.y)>2&&Math.hypot(p.x-player.x,p.y-player.y)<9);if(loc)this.play(this.choose('environment',4),{vol:.55,pos:loc,wet:.62});}
 },
 end(won){if(!this.ctx)return;this.active=false;const t=this.ctx.currentTime;this.musicDuck.gain.cancelScheduledValues(t);this.musicDuck.gain.setTargetAtTime(won?.28:.06,t,.16);if(won)this.play('seal',{vol:.95,wet:.65});else{if(this.painVoice){try{this.painVoice.source.stop();}catch{}}this.play('agony',{vol:1.03,wet:.22});this.play('bodyfall',{vol:.8,at:t+.45,wet:.4});}}
};

