// combat.js — bundled from the owner’s liminal baseline.
function changeWeapon(n){if(s4dLocked()||mode!=='playing')return;const count=s4tCarried()?4:3;n=((n%count)+count)%count;if(n===weapon)return;weapon=n;if(n<3)S4T.previousGun=n;reloadT=reloadDuration=0;weaponDrop=.2;shotCD=Math.max(shotCD,.16);if(n<3)audio.reload('end');else audio.seraphimCue('throw');hudUpdate();}
function reload(){if(s4dLocked()||weapon===3)return;const g=guns[weapon];if(review.active&&review.unlimited)g.reserve=g.maxReserve;if(mode!=='playing'||reloadT>0||g.ammo===g.mag||g.reserve<=0)return;reloadT=reloadDuration=g.reload*mods.reload;audio.reload();}
function alertNoise(x,y,radius){for(const e of enemies){if(!e.alive||e.noticed||e.dormant)continue;if(e.enc&&!CH.live[e.enc])continue;const d=Math.hypot(e.x-x,e.y-y);if(d>radius)continue;if(d<radius*.6||lineOfSight(x,y,e.x,e.y)){e.noticed=true;e.alertT=rand(.15,.6);}}}
function emit(x,y,z,col,count=12,power=1){for(let i=0;i<count;i++){if(particles.length>440)particles.shift();const a=rand(0,TAU),sp=rand(.3,3.4)*power;particles.push({x,y,z,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,vz:rand(.2,3.6)*power,life:rand(.2,.6),max:.6,size:rand(.016,.05)*power,color:col});}}
function ring(x,y,color,radius=2,life=.35){rings.push({x,y,color,radius,life,max:life});}
function damageEnemy(e,amount,push=0){if(!e.alive)return;if(e.s4Quest&&e.dormant)s4qWake(e.s4Group);if(e.dormant){hitmarker=.12;if(Math.random()<.5)audio.flesh(e);emit(e.x,e.y,.9,'#8d9a86',5,.5);return;}e.noticed=true;e.alertT=.2;if(e.enc&&typeof CH!=='undefined'&&CH.live&&!CH.live[e.enc]&&typeof chActivate==='function')chActivate(e.enc);e.hp-=amount*mods.damage;e.hurt=.14;e.noticed=true;hitmarker=.12;const d=Math.hypot(e.x-player.x,e.y-player.y)||1;if(push)move(e,(e.x-player.x)/d*push,(e.y-player.y)/d*push);if(e.hp<=0)killEnemy(e);}
function killEnemy(e){if(!e.alive)return;if(typeof CH!=='undefined'&&CH.counter){chCounterKill(e);return;}e.alive=false;e.death=.38;kills++;stageKills++;combo=comboT>0?combo+1:1;comboT=3.4;maxCombo=Math.max(maxCombo,combo);const close=Math.hypot(e.x-player.x,e.y-player.y)<2.1;const earned=hbReward(e,Math.round(creatureTypes[e.type].score*(1+Math.min(combo-1,15)*.2)*(close?1.35:1)));score+=earned;const heal=(18+(e.type===2?7:0)+(close?5:0))*mods.life;player.hp=Math.min(100,player.hp+heal);for(let i=0;i<3;i++){const g=guns[i],gain=i===0?3:i===1?12:(kills%3===0?1:0);g.reserve=Math.min(g.maxReserve,g.reserve+gain);}emit(e.x,e.y,.55,creatureTypes[e.type].color,32,e.type===2?1.45:1);emit(e.x,e.y,.7,'#f3e5c7',10,.8);ring(e.x,e.y,creatureTypes[e.type].color,.8,.24);decals.push({x:e.x,y:e.y,r:rand(.22,.4),color:e.type===1?'#137888':'#781653'});if(decals.length>80)decals.shift();numbers.push({x:e.x,y:e.y,z:1.15,text:'+'+earned,color:'#d5ff42',life:.75});hitstop=.025;killmarker=.2;shake=Math.max(shake,2.6);audio.kill(e);feed((close?'POINT BLANK +35%\n':'')+'SIGNAL +'+Math.round(heal)+(combo>1?' / '+combo+' KILL CHAIN':''));if(combo===3||combo===6||combo===10||combo%15===0)say(combo>=10?'CATASTROPHIC.':combo>=6?'KEEP. FEEDING.':'BLOOD IN THE CIRCUIT.',1.2);if(e.s4Quest)s4qProgress();if(chRunning()){chKill(e);return;}if(fvRunning()||hwRunning()||s4Running())return;if((!review.active||!reviewFixture())&&stageKills>=quotas[stage]&&!cleared){cleared=true;score+=1000;player.hp=Math.min(100,player.hp+20);say('SEAL BROKEN // FIND THE EXIT',2.8);audio.seal();}}
function shoot(){if(s4dLocked()||(s4tRunning()&&S4T.throwLatch))return;if(weapon===3){s4tThrow();return;}if(review.active&&review.unlimited)for(const g of guns)g.reserve=g.maxReserve;if(mode!=='playing'||shotCD>0||reloadT>0||meleeT>.1)return;const g=guns[weapon];if(g.ammo<=0){if(g.reserve>0)reload();else{shotCD=.22;audio.dry();feed('EMPTY // Q MELEE TO REFILL');}return;}g.ammo--;alertNoise(player.x,player.y,weapon===0?20:weapon===1?14:26);shotCD=g.rate;recoil=1;muzzle=weapon===1?.07:.14;shake=Math.max(shake,weapon===0?4:weapon===1?1.7:7);audio.fire(weapon);if(typeof rsShoot==='function'&&rsRunning()){rsShoot(g);if(g.ammo===0&&g.reserve>0)feed('R TO RELOAD / SWITCH WEAPONS');hudUpdate();return;}const origin=hbFighting()||cbRunning()?0:.3,ox=player.x+Math.cos(player.a)*origin,oy=player.y+Math.sin(player.a)*origin;
 if(weapon===0){let got=false,bossDamage=0,bossPoint=null;const totals=new Map();for(let i=0;i<g.pellets;i++){const a=player.a+(i/(g.pellets-1)-.5)*g.spread+rand(-.012,.012),dx=Math.cos(a),dy=Math.sin(a),hit=castRay(player.x,player.y,dx,dy,12);let closest=hit.d,enemy=null,boss=cbRay(player.x,player.y,dx,dy,hit.d+.03)||hbRay(player.x,player.y,dx,dy,hit.d+.03);if(boss)closest=boss.d;for(const e of enemies){if(!e.alive||e.wgGuide)continue;const ex=e.x-player.x,ey=e.y-player.y,along=ex*dx+ey*dy,across=Math.abs(ex*dy-ey*dx);if(along>.1&&along<closest&&across<e.r+.13&&lineOfSight(player.x,player.y,e.x,e.y)){closest=along;enemy=e;boss=null;}}if(enemy){got=true;totals.set(enemy,(totals.get(enemy)||0)+g.damage*clamp(1-closest*.038,.48,1));}else if(boss){bossDamage+=g.damage*clamp(1-closest*.038,.48,1);bossPoint=boss;}else if(i%3===0)emit(player.x+dx*(closest-.03),player.y+dy*(closest-.03),.5,g.color,4,.4);if(i%4===0)tracers.push({x:player.x+dx*closest,y:player.y+dy*closest,z:.5,life:.07,color:g.color});}for(const[e,damage]of totals){damageEnemy(e,damage,.16);emit(e.x,e.y,.65,g.color,9,.65);}if(bossDamage>0)(bossPoint.cerberus?cbDamage:hbDamage)(bossDamage,bossPoint,'shotgun');if(got)audio.flesh();
 }else bullets.push({x:ox,y:oy,a:player.a+rand(-.007,.007),speed:weapon===1?21:11,damage:g.damage,kind:weapon===1?'plasma':'grave',life:2.5,r:weapon===1?.1:.22,owner:'player',color:g.color,z:.52});
 if(g.ammo===0&&g.reserve>0)feed('R TO RELOAD / SWITCH WEAPONS');hudUpdate();}
function melee(){if(typeof rsEncounterMelee==='function'&&rsRunning())return rsEncounterMelee();if(s4dLocked()||weapon===3)return;if(mode!=='playing'||meleeCD>0)return;alertNoise(player.x,player.y,5);meleeT=.27;meleeCD=.62;shake=Math.max(shake,3);audio.swing();let hit=false;for(const e of enemies){if(!e.alive||e.wgGuide)continue;const d=Math.hypot(e.x-player.x,e.y-player.y),a=angle(Math.atan2(e.y-player.y,e.x-player.x)-player.a);if(d<1.5&&Math.abs(a)<.85&&lineOfSight(player.x,player.y,e.x,e.y)){damageEnemy(e,65,.48);emit(e.x,e.y,.6,'#ff327c',18);hit=true;}}const boss=cbRay(player.x,player.y,Math.cos(player.a),Math.sin(player.a),1.35)||hbRay(player.x,player.y,Math.cos(player.a),Math.sin(player.a),1.35);if(boss)(boss.cerberus?cbDamage:hbDamage)(45,boss,'melee');if(hit){audio.flesh(null,true);guns[0].reserve=Math.min(72,guns[0].reserve+3);feed('MELEE // +3 SHELLS');}}
function dash(){if(s4dLocked())return;if(mode!=='playing'||dashCD>0)return;let x=(keys.KeyD?1:0)-(keys.KeyA?1:0)+touchMove.x,y=(keys.KeyW?1:0)-(keys.KeyS?1:0)-touchMove.y;if(Math.hypot(x,y)<.1){x=0;y=1;}const len=Math.hypot(x,y);player.vx=(Math.cos(player.a)*y-Math.sin(player.a)*x)/len*16;player.vy=(Math.sin(player.a)*y+Math.cos(player.a)*x)/len*16;if(tfRunning()||(liminal.fed&&liminal.fed.locked)){player.vx=Math.abs(player.vx);}dashT=.17;dashCD=1.25*mods.dash;audio.dash();shake=Math.max(shake,1.5);}
function hurtPlayer(amount,reason){if(typeof rsEncounterHurtPlayer==='function'&&rsRunning())return rsEncounterHurtPlayer(amount,reason);if(tfRunning()||(typeof rsRunning==='function'&&rsRunning()))return;if((s4tRunning()&&!cbRunning())||cbfSafe()||s4dLocked()||(S4D.on&&S4D.safeT>0))return;if(hbVictory()||dashT>0||hurt>.22||mode!=='playing'||(review.active&&!review.damage))return;player.hp-=amount*[.65,1,1.3][difficulty];hurt=.42;shake=Math.max(shake,5);comboT=Math.max(0,comboT-.45);audio.hit(amount);if(player.hp<=0){player.hp=0;finish(false,reason||'The ward found a way in. Dash through danger and keep feeding your signal.');}}
function explode(q){hbExplosion(q);cbExplosion(q);const big=q.kind==='grave',radius=big?2.65:.45;if(!big&&Math.random()<.5)audio.flesh({x:q.x,y:q.y});ring(q.x,q.y,q.color,radius,big?.48:.18);emit(q.x,q.y,q.z,q.color,big?65:10,big?1.6:.65);if(big){audio.boom(1,{x:q.x,y:q.y});shake=Math.max(shake,clamp(11/Math.max(1,Math.hypot(q.x-player.x,q.y-player.y)),2,9));whiteFlash=.065;}for(const e of enemies){if(!e.alive||e.wgGuide)continue;const d=Math.hypot(e.x-q.x,e.y-q.y);if(d<radius&&lineOfSight(q.x,q.y,e.x,e.y))damageEnemy(e,q.damage*(big?clamp(1-d/radius,.2,1):1),big?.22:.02);}}
function updateBullets(dt){
 if(typeof rsUpdateBullets==='function'&&rsRunning())return rsUpdateBullets(dt);
 // An impact can cross the boss threshold and replace the live shot list.
 // Walk this frame's stable identities; removed shots never run afterward.
 const pending=bullets.slice();
 for(let i=pending.length-1;i>=0;i--){
 const q=pending[i],index=bullets[i]===q?i:bullets.indexOf(q);if(index<0)continue;
 if(q.cancelled||(q.owner==='enemy'&&hbVictory()&&hbInside(q.x,q.y))){bullets.splice(index,1);continue;}q.life-=dt;let done=q.life<=0;const steps=Math.max(1,Math.ceil(q.speed*dt/.1));for(let s=0;s<steps&&!done;s++){const dx=Math.cos(q.a)*q.speed*dt/steps,dy=Math.sin(q.a)*q.speed*dt/steps;const boss=q.owner==='player'?(cbProjectileContact(q,dx,dy)||hbProjectileContact(q,dx,dy)):null;if(boss){if(boss.cerberus)q.cbHit=boss;else q.hbHit=boss;q.x=boss.x-Math.cos(q.a)*.035;q.y=boss.y-Math.sin(q.a)*.035;done=true;break;}if(s4Running()?s4ShotBlocked(q.x+dx,q.y+dy):wall(q.x+dx,q.y+dy)){done=true;break;}q.x+=dx;q.y+=dy;if(q.cb){q.cbTravel+=Math.hypot(dx,dy);q.z=mix(q.cbZ0,.52,Math.min(1,q.cbTravel/q.cbTargetD));}if(q.owner==='enemy'){if(Math.hypot(q.x-player.x,q.y-player.y)<(q.cbYap?.275:.32)){hurtPlayer(q.damage,q.cbYap?'The little head fires through the others. Find the moving gaps; gunfire can stagger all three.':q.cb?'The Shepherd aims before it spits. Move across its salvo, or dash through the gap.':'An Orderly cut your signal. Its acid bolts can be sidestepped or dashed through.');done=true;}}else for(const e of enemies){if(e.alive&&!e.wgGuide&&Math.hypot(q.x-e.x,q.y-e.y)<e.r+q.r){done=true;break;}}}
 if(done){
  // Consume this exact projectile before impact callbacks clear other shots.
  const liveIndex=bullets[index]===q?index:bullets.indexOf(q);if(liveIndex>=0)bullets.splice(liveIndex,1);
  if(q.owner==='player')explode(q);else emit(q.x,q.y,.5,q.color,q.cbYap?2:9,.7);
 }else if(particles.length<440&&Math.random()<(q.cbYap?.14:.7))particles.push({x:q.x,y:q.y,z:q.z,vx:0,vy:0,vz:0,life:.12,max:.12,size:q.r*.4,color:q.color});
 }}

