// enemies.js — bundled from the owner’s liminal baseline.
function enemyAI(dt){if(cbRunning()&&CB.lureCommitted)return;if(review.active&&!review.ai&&liminal.mode!=='mirror')return;flowClock-=dt;if(flowClock<=0){if(liminal.mode!=='mirror'&&enemies.some(e=>e.alive&&!e.dormant&&!fvSuppressed(e)&&(!e.enc||CH.live[e.enc]||e.noticed)))buildFlow();flowClock=.28;}for(const e of enemies){if(!e.alive){e.death=Math.max(0,e.death-dt);continue;}if(fvSuppressed(e)){e.hurt=Math.max(0,e.hurt-dt);e.walk+=dt;continue;}if(e.dormant){e.hurt=Math.max(0,e.hurt-dt);e.walk+=dt;continue;}if(liminal.mode==='mirror'){mirrorEnemy(e,dt);continue;}e.hurt=Math.max(0,e.hurt-dt);e.cd-=dt;e.vocal-=dt;e.walk+=dt;const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||.01,sees=d<13&&lineOfSight(e.x,e.y,player.x,player.y);if(e.enc&&!CH.live[e.enc]&&!e.noticed)continue;if(sees||d<5){if(!e.noticed)e.alertT=.35;e.noticed=true;}if(!e.noticed)continue;if(e.alertT>0){e.alertT-=dt;if(e.alertT<=0)for(const o of enemies){if(o===e||!o.alive||o.noticed||o.dormant)continue;if(o.enc&&!CH.live[o.enc])continue;if(Math.hypot(o.x-e.x,o.y-e.y)<6.5&&lineOfSight(e.x,e.y,o.x,o.y)){o.noticed=true;o.alertT=.5;}}}if(e.vocal<=0&&d<8){audio.creature(e);e.vocal=rand(3,7);}if(e.hurt>.045)continue;
 if(e.windup>0){e.windup-=dt;if(e.windup<=0){if(e.type===2){const a=Math.atan2(dy,dx);for(let i=-1;i<=1;i++)bullets.push({x:e.x+Math.cos(a)*.35,y:e.y+Math.sin(a)*.35,a:a+i*.15,speed:4.7,damage:14,kind:'acid',life:3,r:.14,owner:'enemy',color:'#caff47',z:.58});e.cd=2.2;}else{e.charge=.32;e.dx=dx/d;e.dy=dy/d;e.cd=2;}}continue;}
 if(e.charge>0){e.charge-=dt;move(e,e.dx*6.8*dt,e.dy*6.8*dt);if(d<.7){hurtPlayer(creatureTypes[e.type].damage);e.charge=0;}continue;}
 if(e.type===2&&sees&&d>2.5&&d<8&&e.cd<=0){e.windup=.7;audio.creature(e,true);continue;}
 if(e.type===1&&sees&&d>1.3&&d<4.1&&e.cd<=0){e.windup=.32;audio.creature(e,true);continue;}
 if(d<.78&&e.cd<=0){hurtPlayer(creatureTypes[e.type].damage);e.cd=e.type===2?1.15:.8;audio.creature(e,true);continue;}
 if(d>.6){let mx=dx/d,my=dy/d;if(!sees||!clearFurniturePath(e.x,e.y,player.x,player.y,e.r)){const ix=e.x|0,iy=e.y|0;let best=flow[iy*MW+ix],tx=e.x,ty=e.y;for(const [xx,yy]of[[ix+1,iy],[ix-1,iy],[ix,iy+1],[ix,iy-1]]){const v=flow[yy*MW+xx];if(v>=0&&(v<best||best<0)){best=v;tx=xx+.5;ty=yy+.5;}}const dd=Math.hypot(tx-e.x,ty-e.y)||1;mx=(tx-e.x)/dd;my=(ty-e.y)/dd;}
 let speed=creatureTypes[e.type].speed*(1+stage*.1)*[.82,1,1.12][difficulty];if(e.type===0)speed*=Math.sin(e.walk*10+e.phase)>.2?1.5:.6;if(e.type===2&&sees&&d<4)speed*=.35;for(const other of enemies){if(!other.alive||other===e)continue;const xx=e.x-other.x,yy=e.y-other.y,sep=Math.hypot(xx,yy);if(sep>.02&&sep<.55){mx+=xx/sep*(.55-sep)*2;my+=yy/sep*(.55-sep)*2;}}if(nowTime<flinchUntil&&d<2.5){mx=-mx;my=-my;speed*=.72;}move(e,mx*speed*dt,my*speed*dt);}
}}

