// run.js — bundled from the owner’s liminal baseline.
function startRun(){applyDifficulty();useChapter=true;review.active=false;document.body.classList.remove('testing');$('reviewBar').classList.add('hidden');$('reviewPanelBtn').classList.add('hidden');$('scoreLabel').textContent='SCORE';$('restartBtn').textContent='RESTART RUN';$('retryBtn').textContent='ONE MORE RUN';audio.reset();Object.assign(mods,{damage:1,speed:1,life:1,reload:1,dash:1});for(const g of guns){g.ammo=g.mag;g.reserve=Math.min(g.maxReserve,g.mag*8);}gameTime=score=kills=combo=maxCombo=comboT=0;weapon=0;loadStage(0);hideOverlays();mode='playing';$('hud').classList.remove('hidden');$('touch').classList.remove('hidden');document.body.classList.add('playing');audio.start();if(review.active)reviewHud();lockPointer();}
function hideOverlays(){for(const id of['start','pause','settings','upgrade','end','testWard','mapPanel'])$(id).classList.add('hidden');}
function lockPointer(){canvas.focus?.({preventScroll:true});if(!coarse&&canvas.requestPointerLock){try{const promise=canvas.requestPointerLock();if(promise?.catch)promise.catch(()=>feed('MOUSE CAPTURE UNAVAILABLE\nDRAG TO AIM / ARROWS TO TURN'));}catch{feed('DRAG TO AIM / ARROWS TO TURN');}}}
function releaseInputs(){mouseFire=false;s4tReleaseTrigger();for(const k in keys)delete keys[k];touchMove.x=touchMove.y=0;lookDelta=0;mapHeld=false;touchLook.id=null;stickId=null;$('stickKnob').style.transform='';}
function pauseGame(){if(mode!=='playing')return;mode='paused';releaseInputs();hideOverlays();$('pause').classList.remove('hidden');$('touch').classList.add('hidden');document.body.classList.remove('playing');document.exitPointerLock?.();audio.pause();}
function resumeGame(){hideOverlays();mode='playing';$('touch').classList.remove('hidden');document.body.classList.add('playing');audio.start();lockPointer();}
function finish(won,reason){if(mode!=='playing')return;mode=won?'won':'dead';releaseInputs();document.exitPointerLock?.();document.body.classList.remove('playing');$('touch').classList.add('hidden');hideOverlays();$('end').classList.remove('hidden');$('endLabel').textContent=won?'THREE SEALS / ONE SURVIVOR':'SIGNAL LOST';$('endTitle').textContent=won?'DISCHARGED.':'BACK TO ASH.';$('endReason').textContent=won?'The ward is quiet. For now.':reason;$('endScore').textContent=Math.round(score).toLocaleString();$('endKills').textContent=kills;$('endTime').textContent=formatTime(gameTime);$('endCombo').textContent=maxCombo+'×';if(!review.active&&score>best){best=Math.round(score);try{localStorage.setItem('ashfall-best-v2',best);}catch{}}if(review.active){$('endLabel').textContent='TEST WARD / '+BUILD.id;$('endTitle').textContent=won?'SCENE COMPLETE.':'TEST ENDED.';$('endReason').textContent=won?'Exit reached. Reset this scene or return to Test Ward.':'Retry this scene, or use Test Ward to change the conditions.';}$('retryBtn').textContent=review.active?'RETRY TEST SCENE':won?'NEW RUN':'RETRY CHECKPOINT';audio.end(won);}
function completeWard(){if(mode!=='playing'||!cleared||s4Running())return;if(hwRunning()){hwComplete();return;}if(fvRunning()){if(review.active){fvComplete();return;}fvHandOver();}if(chRunning()){if(review.active){chComplete();return;}chHandOver();}if(review.active){finish(true);return;}if(stage===2){score+=Math.round(5000+player.hp*20);finish(true);return;}mode='upgrade';releaseInputs();document.exitPointerLock?.();document.body.classList.remove('playing');$('touch').classList.add('hidden');hideOverlays();$('upgrade').classList.remove('hidden');$('wardCleared').textContent=chRunning()?'ADMISSIONS COMPLETE':fvRunning()?'FEVER THEATRE COMPLETE':'SEAL 0'+(stage+1)+' BROKEN';const options=[['HOT BLOOD','25% more damage. Reload 20% faster.',()=>{mods.damage*=1.25;mods.reload*=.8;}],['BAD REFLEXES','Move 15% faster. Dash recharges 30% sooner.',()=>{mods.speed*=1.15;mods.dash*=.7;}],['SECOND HEART','Kills restore 35% more life.',()=>{mods.life*=1.35;}]];$('upgradeList').replaceChildren();for(const [name,desc,fn]of options){const b=document.createElement('button');b.className='upgrade';const st=document.createElement('strong');st.textContent=name;const sp=document.createElement('span');sp.textContent=desc;b.append(st,sp);b.onclick=()=>{fn();loadStage(stage+1);resumeGame();};$('upgradeList').append(b);}audio.pause();}
function formatTime(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}


