// simulation.js — bundled from the owner’s liminal baseline.
function update(dt){audio.tick(dt);liminalTick(dt);if(mode!=='playing')return;if(s4dLocked()){gameTime+=dt;stageTime+=dt;s4dTick(dt);hudUpdate();return;}if(hitstop>0){hitstop-=dt;return;}chTick(dt);fvTick(dt);hwTick(dt);s4Tick(dt);s4dTick(dt);s4tTick(dt);cbTick(dt);if(mode!=='playing')return;reviewTick(dt);gameTime+=dt;stageTime+=dt;grace=Math.max(0,grace-dt);
 if(keys.ArrowLeft)player.a-=dt*2.2;if(keys.ArrowRight)player.a+=dt*2.2;player.a=angle(player.a);aimPitch*=Math.exp(-dt*5);sway=mix(sway,clamp(lookDelta*.03,-1,1),1-Math.exp(-dt*10));lookDelta=0;
 const mx=(keys.KeyD?1:0)-(keys.KeyA?1:0)+touchMove.x,my=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-touchMove.y,len=Math.max(1,Math.hypot(mx,my)),speed=4.65*mods.speed;
 if(dashT>0){dashT-=dt;}else{const a=1-Math.exp(-dt*20);let _tvx=(Math.cos(player.a)*my-Math.sin(player.a)*mx)/len*speed,_tvy=(Math.sin(player.a)*my+Math.cos(player.a)*mx)/len*speed;if((liminal.fed&&liminal.fed.locked)||(typeof CH!=='undefined'&&CH.tr&&CH.tr.fed))_tvx=Math.abs(_tvx);player.vx=mix(player.vx,_tvx,a);player.vy=mix(player.vy,_tvy,a);}move(player,player.vx*dt,player.vy*dt);if(fits(player.x,player.y)){_safeX=player.x;_safeY=player.y;}else if(_safeX!==null){player.x=_safeX;player.y=_safeY;player.vx=player.vy=0;}const moving=Math.hypot(player.vx,player.vy);bob+=dt*moving*2.5;
 shotCD=Math.max(0,shotCD-dt);dashCD=Math.max(0,dashCD-dt);meleeCD=Math.max(0,meleeCD-dt);meleeT=Math.max(0,meleeT-dt);weaponDrop=Math.max(0,weaponDrop-dt);recoil=Math.max(0,recoil-dt*(weapon===1?7:5));muzzle=Math.max(0,muzzle-dt);shake*=Math.exp(-dt*15);hurt=Math.max(0,hurt-dt);hitmarker=Math.max(0,hitmarker-dt);killmarker=Math.max(0,killmarker-dt);whiteFlash=Math.max(0,whiteFlash-dt);comboT=Math.max(0,comboT-dt);if(comboT<=0)combo=0;msgT=Math.max(0,msgT-dt);feedT=Math.max(0,feedT-dt);
 if(reloadT>0&&weapon<3){reloadT-=dt;if(reloadT<=0){const g=guns[weapon],n=Math.min(g.mag-g.ammo,g.reserve);g.ammo+=n;g.reserve-=n;audio.reload('end');}}if(mouseFire||keys.KeyF)shoot();enemyAI(dt);if(mode!=='playing')return;updateBullets(dt);updateEffects(dt);if(cleared&&Math.hypot(player.x-exit.x,player.y-exit.y)<.75)completeWard();hudClock-=dt;if(hudClock<=0){hudUpdate();hudClock=.06;}}


